[theme]
base = "light"
primaryColor = "#8A4B38"
backgroundColor = "#F7F4F0"
secondaryBackgroundColor = "#EEE8E1"
textColor = "#26211E"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
